### ISSUE TITLE
Attribute is not a number

### ISSUE THREAD

**Issue by denzelem** [makandra/active_type#193]
I noticed that the `validate_numericality_of` matcher from [shoulda_matcher](https://github.com/thoughtbot/shoulda-matchers/blob/6f4de5ad6d0d09486c2c713fb1a0bf38169d399e/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb) does not work with an instance of an `ActiveType` record.

The reason for this is a [add_disallow_non_numeric_value_matcher](https://github.com/thoughtbot/shoulda-matchers/blob/6f4de5ad6d0d09486c2c713fb1a0bf38169d399e/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L374C11-L374C49) check in the `shoulda_matcher` gem.

Do you think there are chances to align the behavior in `ActiveType` to an `ActiveRecord` record?

Example:

- User: ActiveRecord
- Hacker: ActiveType::Object

[Screencast from 21.10.2024 14:51:16.webm](https://github.com/user-attachments/assets/157e19eb-dcb4-40ed-8a60-415637604510)

Source: https://github.com/denzelem/active_type_issue_20241021

**Comment by kratob** [comment]
I've dug a bit for the underlying issue, and I'm not sure we're going to fix this. I'll align this with the team, but I think this will open a whole can of worms.

So this has nothing to do with shoulda-matchers; it's simply that the `validates_numericality` matcher actually does not work as you might expect. The validator will never see the non-numerical value that was assigned to the attribute, because we cast to an integer.

This does work for "real" attributes because of this https://github.com/rails/rails/blob/9a9222874ade2d6f300647897a8ad99e1f05aa32/activemodel/lib/active_model/validations/numericality.rb#L125C1-L139C1

We could try to implement `..._came_from_user?` for `ActiveType`, but it feels increasingly difficult to mimick the ever-changing subtleties across ActiveRecord versions. I think the whole mechanism we use for our virtual attributes is not fit for this.
