### ISSUE TITLE
what is a proper way to override attribute?

### ISSUE THREAD

**Issue by niksfirefly** [makandra/active_type#69]
I have a form where field - ActiveType attribute password - value may come empty
so what is a proper way to override attribute? or set default when attribute empty?
for now I am doing this and it works
```
  def password=(value)
    super
    write_virtual_attribute(:password, generate_password) if value.empty?
  end
```

I wonder is it good solution?

**Comment by mattbrictson** [comment]
It might be better to use a `before_validation` callback?

**Comment by henning-koch** [comment]
In original ActiveRecord, what's the canonical way to override an attribute and call the original setter? Is it `super`? Or just override it and call `write_attribute`?

I'm not sure, and it might have changed across versions of Rails.

**Comment by kratob** [comment]
I would expect this to work:
```
def password=(value)
  new_password = value.presence || generate_password
  super(new_password)
end
```

I'm not quite sure about the canonical way for each Rails version, either.

**Comment by henning-koch** [comment]
You can `super` to call original getters/setters in Rails 3.2 and 4.2.

I think this is better than overriding and calling `write_[virtual_]attribute". @niksfirefly's OP does both, which is certainly unnecessary.

Since `ActiveType::Record` is promoting inheritance as an extension mechanism, we should probably document this and also add some specs to make sure it works with virtual attributes.

**Comment by kratob** [comment]
I've added it to the README; specs already exist.

**Comment by henning-koch** [comment]
Great, thanks!
