### ISSUE TITLE
Expose ActiveRecord::Base.attribute

### ISSUE THREAD

**Issue by Looooong** [makandra/active_type#98]
I want to have custom serialization for my column type in Postgres, so I do this

```rails
class Quiz < ActiveRecord::Base
  # Convert attribute type to Array of Quiz::Choice instead of Array of JSONB
  attribute :choices, ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array.new(ChoiceType.new)
end
```

However, if I switch to `ActiveType::Record`, `::attribute` behaves differently and doesn't serialize the column. I think the `::atttribute` methods from `ActiveRecord::Base` and `ActiveType::Record` must be differentiate from each other and the later must not override the former with different behaviour.

Also, I would love to see that `nests_many` work in conjunction with custom column serializer in this example:

```rails
class Quiz < ActiveType::Record
  # Convert attribute type to Array of Quiz::Choice instead of Array of JSONB
  attribute :choices, ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array.new(ChoiceType.new)
  nests_many :choices
end

class Quiz::Choice < ActiveType::Object
  [...]
end

quiz = Quiz.new
quiz.validate # Should also validate quiz.choices
quiz.choices_attributes = [...] # Assign array of Choice to `choices` column
```

**Comment by kratob** [comment]
I wasn't aware of this use case for `attribute` (having a database column, but overriding the serializer). It might be possible to only do `include ActiveType::NestedAttributes` instead of inheriting from `ActiveType::Record`, in order to get `nests_many`, but not the new behaviour of `attribute`. I have not tested that, though.

I could see three ways to address this
- We offically support `include ActiveType::NestedAttributes`, so users can get `nests_many` without `attribute`.
- We rename our `attribute` method. This is a big breaking change. I'm a bit hesitant to do this for a use case I never had.
- We alias Rails' `attribute` method as `ar_attribute` or something. This is kind of unexpected, but might fix the use case above.

@triskweline Any thoughts?

**Comment by triskweline** [comment]
@kratob Can we support custom serializers in our `attribute` ?

**Comment by Looooong** [comment]
I'm using Rails 4.2.8

@kratob I tested `include ActiveType::NestedAttributes` and it doesn't work :(

@triskweline Having custom serializer for your `attribute` is a good idea. I'd like to also have an ability to persist defined `attribute` to a database column (just assign attribute and let Rails handles the abstraction?).

**Comment by kratob** [comment]
I can look into supporting custom serializers. It would probably require a significant rewrite though, since our `attribute` is not designed to do any serialization at all.

**Comment by triskweline** [comment]
OK, so unless someone wants to attempt a PR with tests, I don't see us implementing this any time soon.

Just so this doesn't trip up people in the future, how about we expose the original method as `ar_attribute` as @kratob. When someone passes a non-symbol type to our `attribute` we could raise an error with instructions to use `ar_attribute` instead.

**Comment by Looooong** [comment]
Sounds good to me. Be aware, in Rails 5, we can use both symbol and type object for custom type, [reference](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute).

**Comment by kratob** [comment]
`ActiveRecord.attribute` is now exposed as `.ar_attribute`. Unfortunately I cannot print any warnings, since an `ActiveModel::Type` *is* valid for the second arguments to `ActiveType.attribute`, it just does not work to override behavior for database-backed columns.

**Comment by kratob** [comment]
(Release as 1.1.0).
